### ISSUE TITLE
Have some tweak for NUXT rendering ? window is not defined

### ISSUE THREAD

**Issue by glad1uss967** [Alucard17/vue-sticky-sidebar#1]

**Comment by davidessayan** [comment]
EDIT: On Nuxt with universal mode enabled, you have to implement plugin using nuxt.config.js.

1) in your /plugins folder, create a `vue-stickysidebar.js` : 
```
import Vue from 'vue'
import VueStickySidebar from 'vue-sticky-sidebar'

Vue.component('vue-sticky-sidebar', VueStickySidebar)
```


2) open your `nuxt.config.js` then add your plugin : 

```
plugins: [
    { src: '~/plugins/vue-stickysidebar.js', mode: 'client' }
]
```


3) you can now use your plugin inside your components this way : 
````
<vue-sticky-sidebar>
    My sidebar content
</vue-sticky-sidebar>
````

**Comment by Alucard17** [comment]
@davidessayan is correct
